# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, mtl, operational, stm, hsSDL2 }:

cabal.mkDerivation (self: {
  pname = "rover";
  version = "0.1.0.0";
  src=./.;
  isLibrary = false;
  isExecutable = true;
  buildDepends = [ mtl operational hsSDL2 stm];
  meta = {
    license = self.stdenv.lib.licenses.unfree;
    platforms = self.ghc.meta.platforms;
  };
})
